version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DATABASE_HOST=mongodb+srv://makuntz:8501142000@cluster0.dmldl.mongodb.net/?retryWrites=true&w=majority
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
